services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    command: ["--config=/etc/otel/config.yml"]
    volumes:
      - ./infra/otel/config.yml:/etc/otel/config.yml:ro
    ports:
      - "4317:4317" # OTLP gRPC ingest
      - "4318:4318" # OTLP HTTP ingest
      - "8888:8888" # métriques internes du collector
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.5.0
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./infra/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo_data:/var/tempo
    ports:
      - "3200:3200" # API/UI Tempo pour Grafana

  prometheus:
    image: prom/prometheus:v2.53.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3004:3000"
    depends_on:
      - prometheus
      - tempo

volumes:
  tempo_data:
  prometheus_data:
  grafana_data:
