kube-prometheus-stack:
  grafana:
    adminPassword: ""

alertmanagerConfig:
  smtp:
    host: ""
    from: "" # must be the verified address of your Brevo account
    username: "<smtp-username-brevo>"
    password: "<smtp-password-brevo>"
    to: ""
